victoricoma/helpr

MySQL/empregados/AulaFiltrosAvancadosEmpregados.sql
MySQL/empregados/AulaFiltrosRelacionamentosTemporarios.sql

Organizando os relacionamentos, criando views e agrupamento.

---

MySQL/empregados/AulaJoins.sql
MySQL/empregados/AulaTabelasTemporarias.sql

Utilização de JOINs e montagem de grupos de seletores

---

MySQL/empregados/AulaBasicoGatilhos.sql
MySQL/empregados/AulaGatilhosBasicos.sql

Utilizando sistemas básicos de gatilhos com banco de dados.

---

MySQL/empregados/AulaGatilhosBasicos.sql

/* Exercício Gatilhos */
/*
1) Criar uma tabela para gerenciar as trocas de departamento. 
(cod_log_depto AI, cod_empregado, emp_troca, dt_troca_depto, depto_antigo, depto_novo, correcao_log BIT)
2) Criar gatilho ver se o departamento é diferente, caso sim insert na tabela log_depto.
3) Transação trocando os depatamentos dos empregados 
Marcos Aparecido 1 -> 2
Antônio Silva 1 -> 2
Felipe Januário 1 -> 4
Alexandra Pereira 1 -> 3
Maria Eduarda Di Senna 1 -> 3
Marcela Marcondes 1 -> 3
*/

Exercitando gatilhos e construção de LOGs de depto.

---

MySQL/empregados/AulaProceduresAvancados.sql
MySQL/empregados/AulaProceduresBasicas.sql

Montagem de procedures avancados e modificadoires de base no Log.

---

src/main/java/com/api/helpr/domain/Chamado.java
src/main/java/com/api/helpr/domain/Cliente.java
src/main/java/com/api/helpr/domain/Pessoa.java
src/main/java/com/api/helpr/domain/Tecnico.java

Adição dos vínculos de ORM a camada de domínio.

---

src/main/java/com/api/helpr/HelprApplication.java
src/main/java/com/api/helpr/repositories/ChamadoRepository.java
src/main/java/com/api/helpr/repositories/ClienteRepository.java
src/main/java/com/api/helpr/repositories/PessoaRepository.java
src/main/java/com/api/helpr/repositories/TecnicoRepository.java
src/main/resources/application.properties

Modelagem daas classes com interfaces de insert no H2 data.

---

src/main/java/com/api/helpr/HelprApplication.java
src/main/java/com/api/helpr/config/TestConfig.java
src/main/java/com/api/helpr/services/DBService.java
src/main/resources/application-test.properties
src/main/resources/application.properties

Postman configurado e serviços de dados criado.

---

src/main/java/com/api/helpr/config/DevConfig.java
src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/services/DBService.java
src/main/java/com/api/helpr/services/TecnicoService.java
src/main/resources/application-dev.properties
src/main/resources/application.properties

Controladores de serviços, perfil de desenvolvimento.

---

src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/resources/exceptions/ResourceExceptionHandler.java
src/main/java/com/api/helpr/resources/exceptions/StandardError.java
src/main/java/com/api/helpr/services/TecnicoService.java
src/main/java/com/api/helpr/services/exceptions/ObjectNotFoundException.java

Modelagem das entregas para front com uso de DTO.

---

src/main/java/com/api/helpr/resources/exceptions/ResourceExceptionHandler.java
src/main/java/com/api/helpr/resources/exceptions/StandardError.java

Tratamento de erro banco para back e handler.

---

src/main/java/com/api/helpr/domain/Tecnico.java
src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/services/TecnicoService.java

Adição via Post das informações de tecnico.

---

src/main/java/com/api/helpr/domain/Pessoa.java
src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/services/TecnicoService.java

Método de criar endpoint de update.
Validação dos dados.

Criação do update do banco via PUT e com as validações.

---

MySQL/script_helpr/log_pessoa_gt.sql
src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/services/TecnicoService.java

Método de delete implementado.
Rotina de log feita no banco.
Verificação de chamado.

Recurso de delete com uso de log para update no banco.

---

src/main/java/com/api/helpr/domain/Cliente.java
src/main/java/com/api/helpr/domain/dtos/ClienteDTO.java
src/main/java/com/api/helpr/resources/ClienteResource.java
src/main/java/com/api/helpr/services/ClienteService.java

CRUD de cliente com base em Tecnicos.

---

src/main/java/com/api/helpr/domain/dtos/ChamadoDTO.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

Busca um chamado via ID no banco.

---

src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

RestController para listagem geral de Chamados

---

src/main/java/com/api/helpr/domain/dtos/ChamadoDTO.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

Criar o endpoint em testes Postman.
Criar classe de RestController.
Criar classe de serviços.
Manipular os ajustes de domínio e repositório.

Adição das validações de chamado e inserção via front POST.

---

pom.xml
src/main/java/com/api/helpr/config/SecurityConfig.java
src/main/java/com/api/helpr/domain/dtos/CredenciaisDTO.java
src/main/java/com/api/helpr/security/JWTUtil.java
src/main/java/com/api/helpr/security/UserSS.java
src/main/java/com/api/helpr/services/ClienteService.java
src/main/java/com/api/helpr/services/DBService.java
src/main/java/com/api/helpr/services/TecnicoService.java
src/main/java/com/api/helpr/services/UserDetailsServiceImpl.java
src/main/resources/application.properties

Configuração de testes de segurança

---

src/main/java/com/api/helpr/config/SecurityConfig.java
src/main/java/com/api/helpr/domain/dtos/CredenciaisDTO.java
src/main/java/com/api/helpr/security/JWTAuthenticationFilter.java
src/main/java/com/api/helpr/security/JWTUtil.java
src/main/java/com/api/helpr/services/UserDetailsServiceImpl.java

Adição do sistema de login com uso de Authorization Token.

---

src/main/java/com/api/helpr/security/JWTAuthorizationFilter.java
src/main/java/com/api/helpr/security/JWTUtil.java
src/main/java/com/api/helpr/services/UserDetailsServiceImpl.java

Método no JwtUtils e classe de Authorization Filter

---

MySQL/script_helpr/log_pessoa_gt.sql
src/main/java/com/api/helpr/config/SecurityConfig.java
src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/services/DBService.java
src/main/resources/application.properties

Adição das notações de filtros de Autorização de endpoints.

---

src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/resources/ClienteResource.java

Alterações em chamado e cliente filtro de POST e PUT contrrole da API

---

src/main/java/com/api/helpr/repositories/ChamadoRepository.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

Relatorio de chamados abertos do cliente #88

---

src/main/resources/application-dev.properties
src/main/resources/application.properties

Deploy nas propriedades do Heroku de perfil de DEV

---

MySQL/script_helpr/tg_log_chamado_prioridade.sql

use helpr_hyrsa;
DELIMITER //
CREATE TRIGGER tg_log_prioridade_chamado BEFORE UPDATE 
ON chamado
FOR EACH ROW
BEGIN
IF(OLD.prioridade <> NEW.prioridade) THEN
INSERT INTO log_chamado_prioridade(data_alteracao, dado_alterado, dado_novo, dev_correcao)
VALUES(NOW(), OLD.prioridade, NEW.prioridade, NULL);
END IF;
END //
DELIMITER ;
use helpr_hyrsa;
select * from log_chamado_prioridade;

Criada trigger de Log Alteracao prioridades

---

src/main/java/com/api/helpr/services/ClienteService.java
src/main/java/com/api/helpr/services/TecnicoService.java

 Imp de encoder JWT no update de Técnico e Cliente 

---

MySQL/script_helpr/sps_tarefas_encerradas_cliente_semanal.sql
src/main/java/com/api/helpr/repositories/ChamadoRepository.java

Conversão da Query do ChamadoRepository para Procedure

---

MySQL/script_helpr/proc_rel_semanal_encerradas_cliente.sql

 Proc para rel semanal encerradas pelo cliente

---

MySQL/script_helpr/sps_tecnicos_andamento.sql
src/main/java/com/api/helpr/repositories/ChamadoRepository.java

Procedure de chamados em andamento por técnicos. [45 pts]

---

MySQL/script_helpr/sps_relatorio_status.sql

Procedure Relatório Status data inicial e final

---

MySQL/script_helpr/tg_log_chamado_Perfil.sql

CREATE TABLE log_chamado_Perfil(
id INT NOT NULL AUTO_INCREMENT,
dt_alteracao DATETIME NOT NULL,
dado_alterado VARCHAR(250) NOT NULL,
novo_dado VARCHAR(250) NOT NULL,
id_pessoa INT NOT NULL,
PRIMARY KEY(id)
);
DELIMITER //
CREATE TRIGGER tg_log_chamado_Perfil BEFORE UPDATE ON pessoa
FOR EACH ROW 
BEGIN
IF(NEW.dtype <> OLD.dtype) THEN
INSERT INTO log_chamado_Perfil(dt_alteracao, dado_alterado,novo_dado, id_pessoa)
VALUES(NOW(), OLD.dtype, NEW.dtype, NEW.id);
END IF;
END //
DELIMITER ;

relatório de update de perfil de Cliente para Tecnico.

---

src/main/java/com/api/helpr/repositories/ChamadoRepository.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

Relatório de Status Logs no Chamado [60 pts]

---

MySQL/script_helpr/sps_relatorio_chamado_aberto_andamento.sql
src/main/java/com/api/helpr/repositories/ChamadoRepository.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

 Montagem do relatório dos Chamados abertos e em andamento

---

src/main/java/com/api/helpr/domain/LogTecnicoExclusao.java
src/main/java/com/api/helpr/repositories/LogTecnicoExclusaoRepository.java
src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/services/TecnicoService.java

Criação de domínio, serviço e recurso para entregar ao front log de exclusão de técnicos [30 pts]

---

src/main/java/com/api/helpr/services/TecnicoService.java

Correção do catalogo de importação do TecnicoService.

---

MySQL/script_helpr/sps_chamados_abertos_soma_dia_tecnico.sql
src/main/java/com/api/helpr/repositories/ChamadoRepository.java

 procedure  relatorio chamados abertos por dia

---

src/main/java/com/api/helpr/domain/LogChamadoPrioridade.java
src/main/java/com/api/helpr/repositories/LogChamadoPrioridadeRepository.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

Montagem domínio serviço  recurso Chamado Prioridade [45pts]

---

src/main/java/com/api/helpr/domain/dtos/PessoaDTO.java
src/main/java/com/api/helpr/resources/PessoaResource.java
src/main/java/com/api/helpr/services/PessoaService.java

Endpoint de pessoa para validar perfil [120 pts]

---

MySQL/script_helpr/sp_rel_chamados_enc_hoje_tecnicos.sql
src/main/java/com/api/helpr/repositories/ChamadoRepository.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

Endpoint Entrega Chamados encerrados hoje tecnicos - [90 pts]

---

src/main/java/com/api/helpr/domain/ClienteFuturo.java

Criação de domain para futuros clientes

---

MySQL/script_helpr/proc_relatorio_semanal_tecnico.sql

Proc de Tarefas Semanais encerradas de técnico

---

MySQL/script_helpr/sps_chamado_titulo.sql
src/main/java/com/api/helpr/repositories/ChamadoRepository.java
src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/services/ChamadoService.java

/service/chamados/titulo/:titulo

Filtro de Chamados por título

---

src/main/java/com/api/helpr/domain/Candidato.java
src/main/java/com/api/helpr/domain/dtos/CandidatoDTO.java
src/main/java/com/api/helpr/repositories/CandidatoRepository.java
src/main/java/com/api/helpr/resources/CandidatoResource.java
src/main/java/com/api/helpr/services/CandidatoService.java
src/main/java/com/api/helpr/services/DBService.java

Criação Candidatos domain,

---

src/main/java/com/api/helpr/domain/dtos/ClienteFuturoDTO.java
src/main/java/com/api/helpr/repositories/ClienteFuturoRepository.java
src/main/java/com/api/helpr/resources/ClienteFuturoResource.java
src/main/java/com/api/helpr/services/ClienteFuturoService.java

Cliente Futuro (Service, Resource, Repository e DTO) [45pts]

---

MySQL/script_helpr/sps_tecnicos_nomes.sql
src/main/java/com/api/helpr/repositories/TecnicoRepository.java
src/main/java/com/api/helpr/resources/TecnicoResource.java
src/main/java/com/api/helpr/services/TecnicoService.java

Criação de método para busca de tecnicos por nome [45pts]

---

MySQL/script_helpr/sps_candidato_byNome.sql
src/main/java/com/api/helpr/repositories/CandidatoRepository.java
src/main/java/com/api/helpr/resources/CandidatoResource.java
src/main/java/com/api/helpr/services/CandidatoService.java

POSTMAN: 
/service/candidatos/(:nome)

Endpoint de busca por nome do candidato

---

src/main/java/com/api/helpr/resources/CandidatoResource.java
src/main/java/com/api/helpr/services/CandidatoService.java

Listagem de Candidatos [30pts]

---

src/main/java/com/api/helpr/resources/ChamadoResource.java
src/main/java/com/api/helpr/resources/ClienteFuturoResource.java

Listagem de futuros clientes através de token [60 pts]

---

src/main/java/com/api/helpr/resources/CandidatoResource.java
src/main/java/com/api/helpr/services/CandidatoService.java

Finalização do CRUD do Candidato
